<?php

use Illuminate\Support\Facades\Route;

// API routes generated by CRUD Builder
// Add your API resource routes below

// Route::apiResource('videos', \App\Http\Controllers\Api\VideoController::class);
